#include <stdio.h>
#include "ccalc.h"

void show_help_functions()
{
    puts("=== MATHEMATICAL FUNCTIONS ===");
    puts("");
    puts("Trigonometric (radians, support complex x|z):");
    puts("  sin(x|z), cos(x|z), tg(x|z)/tan(x|z), ctg(x|z)/cot(x|z)");
    puts("  arcsin(x|z)/asin(x|z), arccos(x|z)/acos(x|z)");
    puts("  arctg(x|z)/atan(x|z), arcctg(x|z)/acot(x|z)");
    puts("");
    puts("Trigonometric (degrees, real only):");
    puts("  sing(x), cosg(x), tgg(x), ctgg(x)");
    puts("");
    puts("Hyperbolic (support complex x|z):");
    puts("  sinh(x|z)/sh(x|z), cosh(x|z)/ch(x|z)");
    puts("  tanh(x|z)/th(x|z), ctanh(x|z)/cth(x|z)");
    puts("  asinh(x|z)/arsh(x|z), acosh(x|z)/arch(x|z)");
    puts("  atanh(x|z)/arth(x|z), acoth(x|z)/arcth(x|z)");
    puts("  atan2(y,x)");
    puts("");
    puts("Exponential & Logarithmic:");
    puts("  exp(x|z)             - e^x (complex support)");
    puts("  exp10(x)             - 10^x");
    puts("  ln(x|z)/log(x|z)     - Natural log (complex support)");
    puts("  lg(x)/log10(x)       - Base 10 log");
    puts("  log2(x)              - Base 2 log");
    puts("  logn(x|z,y|z)        - Base x log (complex support)");
    puts("  sqrt(x|z)/root2(x|z) - Square root (complex support)");
    puts("  root3(x)/cbrt(x)     - Cube root");
    puts("  rootn(x|z,n|z)       - n-th root (complex support)");
    puts("  pow(x|z,y|z)         - x^y (complex support)");
    puts("");
    puts("Rounding & Conversion:");
    puts("  int(x), float(n), round(x), frac(x)");
    puts("  not(n)               - Bitwise NOT, same as ~n");
    puts("");
    puts("Other:");
    puts("  abs(x|z)      - Absolute value / Complex magnitude");
    puts("  fact(n), n!   - Factorial");
    puts("  prime(n)      - Smallest prime >= n");
    puts("  min(x,y), max(x,y)");
    puts("  hypot(x,y)    - Hypotenuse sqrt(x^2+y^2)");
    puts("  erf(x), erfc(x)");
    puts("");
    puts("Complex:");
    puts("  cmplx(x,y)    - Create complex number");
    puts("  re(z)         - Real part");
    puts("  im(z)         - Imaginary part");
    puts("  pol(z)        - Phase angle atan(im/re)");
    puts("  Note: Use i or j for imaginary unit, last used notation is for output");
    puts("");
    puts("Decibels & Engineering:");
    puts("  db(x), adb(x), np(x), anp(x)");
    puts("  Vout(Vref,Rh,Rl)     - Voltage divider: Vref*(Rh+Rl)/Rl");
    puts("  ee(n,x)              - E series of preferred numbers");
    puts("  cs(x), acs(x)        - Cross section / diameter conversion");
    puts("  awg(n), sawg(n), aawg(x)      - American wire gauge");
    puts("  swg(n), sswg(n), aswg(x)      - British standard wire gauge");
    puts("  gcd(n,m), invmod(n,m)");
    puts("");
    puts("Time & Random:");
    puts("  now(n)        - Current Unix time (+/- n hours)");
    puts("  datatime(str) - Parse datetime to Unix time");
    puts("  timezone, daylight, tz");
    puts("  rnd(x)        - Random value 0..x");
    puts("");
    puts("Formatting:");
    puts("  printf(fmt,...), fprn(fmt,...), prn(fmt,...)");
    puts("");
    puts("Special:");
    puts("  help(n)       - Show help page n");
    puts("  opacity(n)    - Set window opacity (0-100)");
    puts("  binwide(n)    - Set binary display width");
    puts("  menu(0/1)     - Hide/Show menu");
    puts("  vars()        - Show variables list");
    puts("  font(n)       - Set font size");
    puts("");
    puts("Note: (x|z) means complex support, (x) real only");
}

void show_help_operators()
{
    puts("=== OPERATORS ===");
    puts("");
    puts("Arithmetic (complex support on +,-,*,/):");
    puts("  +, -                 - Also for strings (concatenation)");
    puts("  *, /, %              - Multiplication, division, remainder");
    puts("  **, ^                - Power (complex support)");
    puts("  ++, --               - Increment/Decrement (prefix & postfix)");
    puts("");
    puts("Bitwise:");
    puts("  ~                    - Complement (complex: conjugate)");
    puts("  &                    - Bitwise AND");
    puts("  |                    - Bitwise OR");
    puts("  #, ^                 - Bitwise XOR");
    puts("  <<                   - Arithmetic shift left");
    puts("  >>                   - Arithmetic shift right");
    puts("  >>>                  - Logical shift right");
    puts("");
    puts("Comparison:");
    puts("  ==, !=, <>           - Equal, Not equal");
    puts("  <, <=, >, >=         - Less, Less/Equal, Greater, Greater/Equal");
    puts("");
    puts("Logical:");
    puts("  !                    - Logical NOT");
    puts("  &&                   - Logical AND");
    puts("  ||                   - Logical OR");
    puts("");
    puts("Assignment:");
    puts("  =                    - Simple assignment");
    puts("  +=, -=, *=, /=, %=   - Compound assignment");
    puts("  **=                  - Power and assign");
    puts("  &=, |=, #=, ^=       - Bitwise compound assignment");
    puts("  <<=, >>=, >>>=       - Shift compound assignment");
    puts("");
    puts("Special:");
    puts("  //                   - Parallel resistors: 1/(1/a+1/b)");
    puts("");
    puts("Pascal mode (/PAS+):");
    puts("  :=                   - Assignment");
    puts("  =                    - Comparison (instead of ==)");
    puts("");
    puts("C mode:");
    puts("  =                    - Assignment");
    puts("  ==                   - Comparison");
    puts("  ^                    - XOR (not power!)");
    puts("  //                   - Parallel resistors");
}

void show_help_formats()
{
    puts("=== NUMBER FORMATS ===");
    puts("");
    puts("Integer formats:");
    puts("  0xFF, $1000          - Hexadecimal");
    puts("  0o77, 01000          - Octal");
    puts("  0b1010               - Binary");
    puts("  123, -456            - Decimal");
    puts("");
    puts("Float formats:");
    puts("  3.14, -2.5, 1.23e-4  - Standard notation");
    puts("  .5, 5.               - Partial notation");
    puts("  1.8e6                - Normalized (1.8*10^6)");
    puts("");
    puts("Scientific notation (/SCI+):");
    puts("  1.8M = 1800000       - SI prefix (M = mega)");
    puts("  2k5 = 2500           - Engineering notation");
    puts("  1k33 = 1330          - Engineering notation");
    puts("");
    puts("Computing notation:");
    puts("  1KB = 1024           - Binary prefix (K = 2^10)");
    puts("  1MB, 1GB, 1TB        - Binary multiples");
    puts("");
    puts("Special formats:");
    puts("  10`20'40\"            - Degrees/minutes/seconds");
    puts("  1:c1:y1:d1:h1:m1:s   - Date/time format");
    puts("  'A', 'AB'            - Character constants");
    puts("  L'c', 'c'W           - Wide character");
    puts("  \"string\"             - String literals");
    puts("  \\377, \\e, \\n, \\xff  - Escape sequences");
    puts("  3+9/64               - Fractional notation");
    puts("  #28                  - Wire gauge (AWG)");
    puts("  2\"5                  - Inch notation");
    puts("");
    puts("Complex numbers:");
    puts("  2+3i, -1-2i          - Rectangular form");
    puts("  i, j                 - Imaginary unit (lowercase only!)");
}

void show_help_constants()
{
    puts("=== PREDEFINED CONSTANTS ===");
    puts("");
    puts("Mathematical:");
    puts("  pi, PI                - π (3.14159265358979...)");
    puts("  e, E                  - Euler's number (2.71828182845904...)");
    puts("  phi                   - Golden ratio (1.618033988749...)");
    puts("  i, j                  - Imaginary unit (√-1)");
    puts("");
    puts("Physical Constants (CODATA 2018):");
    puts("");
    puts("  Fundamental:");
    puts("    c0                  - Speed of light in vacuum (299792458 m/s)");
    puts("    hp                  - Planck constant (6.62607015e-34 J·s)");
    puts("    hb                  - Reduced Planck constant ℏ (1.054571817e-34 J·s)");
    puts("    gn                  - Gravitational constant (6.67430e-11 m³/(kg·s²))");
    puts("    na                  - Avogadro constant (6.02214076e23 mol⁻¹)");
    puts("    kb                  - Boltzmann constant (1.380649e-23 J/K)");
    puts("    rg                  - Universal gas constant (8.314462618 J/(mol·K))");
    puts("");
    puts("  Electromagnetic:");
    puts("    e0                  - Electric constant (8.8541878128e-12 F/m)");
    puts("    u0                  - Magnetic constant (1.25663706212e-6 H/m)");
    puts("    z0                  - Impedance of vacuum (376.730313668 Ω)");
    puts("");
    puts("  Particle:");
    puts("    qe                  - Elementary charge (1.602176634e-19 C)");
    puts("    me                  - Electron mass (9.1093837015e-31 kg)");
    puts("    mp                  - Proton mass (1.67262192369e-27 kg)");
    puts("    mn                  - Neutron mass (1.67492749804e-27 kg)");
    puts("    rel                 - Classical electron radius (2.8179403262e-15 m)");
    puts("    a0                  - Bohr radius (5.29177210903e-11 m)");
    puts("");
    puts("  Astronomical:");
    puts("    au                  - Astronomical unit (1.495978707e11 m)");
    puts("    ly                  - Light year (9.4607304725808e15 m)");
    puts("    pc                  - Parsec (3.0856775814914e16 m)");
    puts("");
    puts("  Additional:");
    puts("    ry                  - Rydberg constant (10973731.568160 m⁻¹)");
    puts("    sb                  - Stefan-Boltzmann constant (5.670374419e-8 W/(m²·K⁴))");
    puts("");
    puts("Integer Limits:");
    puts("  max32, maxint         - Maximum signed 32-bit (2147483647, 0x7FFFFFFF)");
    puts("  maxu32, maxuint       - Maximum unsigned 32-bit (4294967295, 0xFFFFFFFF)");
    puts("  max64, maxlong        - Maximum signed 64-bit (9223372036854775807)");
    puts("  maxu64, maxulong      - Maximum unsigned 64-bit (18446744073709551615)");
    puts("");
    puts("System:");
    puts("  version               - Calculator version");
    puts("  timezone              - System timezone offset in hours");
    puts("  daylight              - Daylight saving time flag (0 or 1)");
    puts("  tz                    - Current timezone with DST applied");
    puts("");
    puts("Note: Constants are predefined variables (can be changed but not recommended).");
    puts("      All constants are case-insensitive with /UPCASE+ option.");
}

void show_help_prefixes()
{
    puts("=== SI PREFIXES (with /SCI+) ===");
    puts("");
    puts("Large (decimal, power of 10):");
    puts("  Y  - yotta  (10^24)");
    puts("  Z  - zetta  (10^21)");
    puts("  E  - exa    (10^18)");
    puts("  P  - peta   (10^15)");
    puts("  T  - tera   (10^12)");
    puts("  G  - giga   (10^9)");
    puts("  M  - mega   (10^6)");
    puts("  k  - kilo   (10^3)");
    puts("  da - deka   (10^1)");
    puts("");
    puts("Small (decimal, power of 10):");
    puts("  d  - deci   (10^-1)");
    puts("  c  - centi  (10^-2)");
    puts("  m  - milli  (10^-3)");
    puts("  u  - micro  (10^-6)");
    puts("  n  - nano   (10^-9)");
    puts("  p  - pico   (10^-12)");
    puts("  f  - femto  (10^-15)");
    puts("  a  - atto   (10^-18)");
    puts("  z  - zepto  (10^-21)");
    puts("  y  - yocto  (10^-24)");
    puts("");
    puts("Binary (power of 2):");
    puts("  YB - yotta  (2^80)");
    puts("  ZB - zetta  (2^70)");
    puts("  EB - exa    (2^60)");
    puts("  PB - peta   (2^50)");
    puts("  TB - tera   (2^40)");
    puts("  GB - giga   (2^30)");
    puts("  MB - mega   (2^20)");
    puts("  KB - kilo   (2^10)");
    puts("");
    puts("Examples:");
    puts("  5k = 5000");
    puts("  2.5M = 2500000");
    puts("  100u = 0.0001");
    puts("  6k8 = 6800 (engineering notation)");
    puts("  1KB = 1024 (binary)");
}

void show_help_examples()
{
    puts("=== EXAMPLES ===");
    puts("");
    puts("Basic arithmetic:");
    puts("  2+2");
    puts("  2^10");
    puts("  sqrt(3^2+4^2)");
    puts("");
    puts("Hex/Binary:");
    puts("  0xFF + 0b1010");
    puts("  0xDEADBEEF & 0xFF");
    puts("");
    puts("Scientific notation:");
    puts("  L:=130u;c:=2.2n;f:=1/(2*pi*sqrt(l*c))    => 297.6k");
    puts("  72-20%                                     => 57.6");
    puts("  72-20%+5%                                  => 60.48");
    puts("  500*5%                                     => 12500");
    puts("  1/2%                                       => 50");
    puts("  57.6%%72                                   => -20");
    puts("");
    puts("Complex numbers:");
    puts("  (2+3i)*(4-5i)");
    puts("  abs(3+4j)                                  => 5");
    puts("  z:=3+4i                                    => 3+4i");
    puts("  sqrt(-1)");
    puts("");
    puts("Implicit multiplication (/IMUL+):");
    puts("  2PI            (= 2*PI)");
    puts("  2sin(PI/4)     (= 2*sin(PI/4))");
    puts("  (1+2)(3+4)     (= (1+2)*(3+4))");
    puts("");
    puts("Variables:");
    puts("  x=5; y=10; x+y");
    puts("  r=10; PI*r^2");
}

void show_help_overview()
{
    puts("=== CALCULATOR HELP ===");
    puts("");
    puts("Available help topics:");
    puts("  help(0)  - This overview");
    puts("  help(1)  - Mathematical functions");
    puts("  help(2)  - Operators");
    puts("  help(3)  - Number formats");
    puts("  help(4)  - Predefined constants");
    puts("  help(5)  - SI prefixes");
    puts("  help(6)  - Usage examples");
    puts("  help(7)  - Calculator options");
    puts("  help(n)  - For any other n, shows all sections");
    puts("");
    puts("Quick start:");
    puts("  2+2                    - Simple calculation");
    puts("  2^8                    - Power");
    puts("  sqrt(2)                - Functions");
    puts("");
    puts("Features:");
    puts("  - C-style expressions with operators and functions");
    puts("  - Complex number support (use i or j)");
    puts("  - Multiple number formats (hex, octal, binary, scientific)");
    puts("  - Variables and assignments");
    puts("  - Implicit multiplication with /IMUL+ (2PI, 2sin(x))");
    puts("  - SI prefixes with /SCI+ (k, M, G, m, u, n, etc.)");
}
void show_options_help()
{
    puts("Calculator Options Help");
    puts("=======================");
    puts("");
    puts("Input/Calculation Options (WO - Write Only):");
    puts("  /PAS+/-   - Pascal assignment and comparison style (:= =) <-> (= ==)");
    puts("  /SCI+/-   - Scientific numbers format (2k == 2000)");
    puts("  /UPCASE+/-- Case insensitive variables");
    puts("  /UTMP+/-  - Using $n for temporary variables");
    puts("  /FFLOAT+/-- Forced float mode");
    puts("  /IMUL+/-  - Implicit multiplication (2sin(x))");
    puts("");
    puts("Format Detection Flags (RO - Read Only, set by parser):");
    puts("  /DEG+/-   - Degrees format found");
    puts("  /SCF+/-   - Scientific (6.8k) format found");
    puts("  /ENG+/-   - Engineering (6k8) format found");
    puts("  /STR+/-   - String format found");
    puts("  /HEX+/-   - Hex format found");
    puts("  /OCT+/-   - Octal format found");
    puts("  /FBIN+/-  - Binary format found");
    puts("  /DAT+/-   - Date time format found");
    puts("  /CHR+/-   - Char format found");
    puts("  /WCH+/-   - WChar format found");
    puts("  /ESC+/-   - Escape format found");
    puts("  /CMP+/-   - Computing format found");
    puts("  /UTM+/-   - Unix time format");
    puts("");
    puts("Output Format Options (UI - User Interface):");
    puts("  /NRM+/-   - Normalized output");
    puts("  /IGR+/-   - Integer output");
    puts("  /UNS+/-   - Unsigned output");
    puts("  /ALL+/-   - Show all output formats");
    puts("  /FRC+/-   - Fraction output");
    puts("  /FRI+/-   - Fraction inch output");
    puts("  /AUTO+/-  - Auto output format");
    puts("");
    puts("UI Options:");
    puts("  /MIN+/-   - Escape minimized feature");
    puts("  /MNU+/-   - Show/hide menu feature");
    puts("  /TOP+/-   - Always on top");
    puts("");
    puts("Other Options:");
    puts("  /BW=n     - Binary width (default 64)");
}

void show_usage()
{
    puts("ccalc - Console Calculator");
    puts("Usage:");
    puts("  ccalc <expression> [/options]");
    puts("  ccalc help(n)  - show help page n");
    puts("");
    puts("IMPORTANT: Always use quotes around expressions!");
    puts("  Symbols like ^, |, &, <, > have special meaning in shell.");
    puts("");
    puts("Examples:");
    puts("  ccalc \"2+2\"");
    puts("  ccalc \"2^2\"        # Power - use quotes!");
    puts("  ccalc \"sqrt(3^2+4^2)\"");
    puts("  ccalc \"0xFF + 0b1010\" /HEX+ /BIN+");
    puts("");
    puts("Quick Options (in ccalc.cfg or command line):");
    puts("  /PAS+/-   - Pascal style (:= =)");
    puts("  /SCI+/-   - Scientific format (2k = 2000)");
    puts("  /IMUL+/-  - Implicit multiplication (2sin(x))");
    puts("  /BW=n     - Binary width (default 64)");
    puts("  /ALL+/-   - Show all output formats");
    puts("  /FRC+/-   - Show fraction format");
    puts("");
    puts("For detailed options help, use: ccalc help(0).");
}
