pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["alternate_forms_for_format_con.htm","Alternate Forms for format Conversion","Alternate Forms for format Conversion Top Previous Next If you use the # flag conversion character, it has the following effect on the argument (a...",""],
["description.htm","Description","Description Top Previous Next Features Scientific Calculator: Support for trigonometric functions, logarithms, exponentials, and more Expression P...",""],
["e_or_e_conversions.htm","%e or %E Conversions","%e or %E Conversions Top Previous Next The argument is converted to match the style [-] d.ddd...e[+/-]ddd where: one digit precedes the decimal po...",""],
["e_series_of_preferred_numbers.htm","E series of preferred numbers","Sever E-series values, 1.0–2.13 E3 E6 E12 E24 E48 E96 E192 1.0 1.0 1.0 1.0 1.00 1.00 1.00 1.01 1.02 1.02 1.04 1.05 1.05 1.05 1.06 1.07 1.07 1.09 1...",""],
["fcalc_ftsearch.htm","Scientific formula calculator","Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this...",""],
["format_conversion-type_charact.htm","Format Conversion-Type Characters","Format Conversion-Type Characters Top Previous Next The information in this table is based on the assumption that no flag characters, width specif...",""],
["format_flag.htm","Format flag","Format flag Top Previous Next They can appear in any order and combination. Flag What it means - Left-justifies the result, pads on the right with...",""],
["format_input-size_modifiers.htm","Format Input-size Modifiers","Format Input-size Modifiers Top Previous Next These modifiers determine how printf functions interpret the next input argument, arg[f]. Prefix For...",""],
["format_precision_specifiers.htm","Format Precision Specifiers","Format Precision Specifiers Top Previous Next The printf precision specifiers set the maximum number of characters (or minimum number of integer d...",""],
["format_printf.htm","Printf","format specifiers Top Previous Next format specifiers have the following form % [flags] [width] [.prec] [F|N|h|l|L] type_char Each format specifie...",""],
["format_specifier_conventions.htm","Format Specifier Conventions","Format Specifier Conventions Top Previous Next Certain conventions accompany some of the printf format specifiers for the following conversions: %...",""],
["format_width_specifiers.htm","Format Width Specifiers","Format Width Specifiers Top Previous Next The width specifier sets the minimum field width for an output value. Width is specified in one of two w...",""],
["f_conversions.htm","%f Conversions","%f Conversions Top Previous Next The argument is converted to decimal notation in the style [-] ddd.ddd... where the number of digits after the de...",""],
["g_or_g_conversions.htm","%g or %G Conversions","%g or %G Conversions Top Previous Next The argument is printed in style e, E or f, with the precision specifying the number of significant digits....",""],
["introduction.htm","Introduction","Introduction Top Next Input for this calculator are normal C expressions containing operators, float or integer constants, variables. Precedence a...",""],
["user_constants_and_functions.htm","User constants and functions","User constants and functions Top Previous Next ;; This text file must be located in the directory containing the calculator executable. ;; It cont...",""],
["variables.htm","Variables","View all defined variables and its values. ",""],
["x_or_x_conversions.htm","%x or %X Conversions","%x or %X Conversions Top Previous Next For x conversions, the letters a, b, c, d, e, and f appear in the output. For X conversions, the letters A,...",""]];
